---
title: "Reproducible document"
author: "Johanne Sloth Lauszus"
format: html
---
- Johanne Sloth Lauszus
- Aarhus Universitet
- Lever-, Mave- og Tarmmedicinsk afdeling, AUH

# Introduction
Insert a **super great** introduction *here*

# Methods and results
Can **you** help me calculate *this*

## Analysis
```{r}
2+2
```

# Discussion
Let's **discuss** this a *little* further


```{r setup}
#| message: FALSE
#| warning: FALSE
library(tidyverse)
library(NHANES)
NHANES_small <- read_csv(here::here("data/NHANES_small.csv"))
```

```{r}
NHANES_small <- select(NHANES_small, age, sex, bmi, diabetes, phys_active, bp_sys_ave, bp_dia_ave, education)
NHANES_small
```


```{r}
2 + 2
```
# Table of results

```{r}
NHANES_small %>%
  filter(!is.na(diabetes)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  knitr::kable(caption = "Mean values of Age and BMI for each education and diabetes status")
```

## Prettier table

```{r}
#| echo: false
#| message: FALSE
NHANES_small %>%
  filter(!is.na(diabetes), !is.na(education)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(
    # Task 2a.
    mean_age = round(mean_age, 1),
    mean_bmi = round(mean_bmi, 1),
    # Task 2b.
    education = str_to_sentence(education)
  ) %>%
  rename(
    # Task 3.
    "Diabetes Status" = diabetes,
    "Education" = education,
    "Mean Age" = mean_age,
    "Mean BMI" = mean_bmi
  ) %>%
  knitr::kable(caption = "Mean values of Age and BMI for each education and diabetes status.")
```
